### ISSUE TITLE
Confusing and misleading repo name

### ISSUE THREAD

**Issue by uklotzde** [kartevonmorgen/kvm-interface#1]
In the context of the *kartevonmorgen* organization the name of this repo is confusing and misleading. The name of the repo should reflect the purpose from the viewpoint within this organization, e.g. ~~"wp-events-plugin"~~ "wp-upload-plugin" or similar.

**Comment by sjoerdtakken** [comment]
I can understand that, but with the name "wp-upload-plugin" I have a problem, because this name is confusing in the context of a wordpress website with its plugins. (The name of the repository is also the name of the Wordpress plugin)

For me the question is, if it the right to put all this wordpress plugins under kartevonmorgen. All the other names are also less or more confusing in the context of "kartevonmorgen". Maybe it needs an own organisation on github.. 
Alternativ I can also rename all the plugins with the prefix "wp-" before it. So in this case you get "wp-kvm-interface"

**Comment by sjoerdtakken** [comment]
I now give all the Wordpress Plugins the prefix "wp-". So it is more clear.
